import pyautogui as pg 
import time

pg.press("win")
time.sleep(2)
pg.write("Google Chrome")
time.sleep(3)
pg.press("enter")
time.sleep(7)
pg.write("https://drive.google.com/drive/folders/1HKMcei20-ZBfKRnJ8_BPaxOz25QC8Zpc")
time.sleep(2)
pg.press("enter")
time.sleep(7)
loc1 = pg.locateOnScreen("plan_3.png")
loc1_center = pg.center(loc1)
pg.click(loc1_center, clicks=2)
time.sleep(10)
loc2 = pg.locateOnScreen("base1.png")
loc2_center = pg.center(loc2)
pg.click(loc2_center)
time.sleep(2)
loc3 = pg.locateOnScreen("download.png")
loc3_center = pg.center(loc3)
pg.click(loc3_center)
time.sleep(10)
pg.keyDown("win")
pg.press("e")
pg.keyUp("win")
time.sleep(10)
loc4 = pg.locateOnScreen("pasta_download.png")
loc4_center = pg.center(loc4)
pg.click(loc4_center)
time.sleep(2)
pg.keyDown("ctrl")
pg.press("a")
time.sleep(2)
pg.press("x")
pg.keyUp("ctrl")
time.sleep(7)
pg.click(x=1364, y=738)
time.sleep(4)
loc5 = pg.locateOnScreen("pasta_base.png")
loc5_center = pg.center(loc5)
pg.click(loc5_center, clicks= 2)
time.sleep(5)
pg.keyDown("ctrl")
pg.press("v")
pg.kayup("ctrl")
